name: flutter_arch
description: An example of Nabeel's Flutter architechture

publish_to: "none"

version: 0.0.1+1

environment:
    sdk: ">=2.17.5 <3.0.0"

dependencies:
    auto_route: ^4.2.0
    cached_network_image: ^3.2.1
    dio: ^4.0.6
    envify: ^2.0.2
    flutter:
        sdk: flutter
    flutter_bloc: ^8.0.1
    flutter_hooks: ^0.18.5+1
    fpdart: ^0.1.0
    freezed_annotation: ^1.1.0
    get_it: ^7.2.0
    injectable: ^1.5.3
    json_annotation: ^4.5.0
    url_launcher: ^6.1.4

dev_dependencies:
    auto_route_generator: ^4.2.0
    build_runner: ^2.1.11
    envify_generator: ^2.0.2
    flutter_gen_runner: ^4.3.0
    flutter_launcher_icons: ^0.9.3
    flutter_native_splash: ^2.2.3+1
    flutter_test:
        sdk: flutter
    freezed: ^1.1.0
    injectable_generator: ^1.5.2
    json_serializable: ^6.2.0
    lint: ^1.8.2

flutter:
    uses-material-design: true

    assets:
        - assets/icon.png

flutter_icons:
    android: true
    ios: true
    image_path: assets/icon.png

flutter_native_splash:
    color: '#ffffff'
    image: assets/icon.png
